Proxy user badge
e-valuation/EvaP pull request #1501
Opened 2020-08-27 18:53 UTC by JannisBerndt

Fixes #1363

2020-08-31 15:12 UTC, He3lixxx approved these changes

2020-08-31 15:46 UTC, janno42 requested changes

2020-08-31 15:46 UTC, janno42 commented on evap/staff/templates/staff_user_badges.html
> +    {% if user.is_proxy_user %}
please move this between "Responsible" and "External"

2020-09-07 15:01 UTC, janno42 approved these changes

2020-09-07 15:02 UTC, merged