Fix two different duplicate contributor messages. Fixes #1082
e-valuation/EvaP pull request #1541
Opened 2020-11-30 18:28 UTC by FSadrieh

Fixes #1082

2020-11-30 21:51 UTC, janno42 requested changes
Nice! Just a very small change request.

2020-11-30 21:51 UTC, janno42 commented on evap/staff/forms.py
> +
please remove these extra lines

2020-11-30 22:19 UTC, FSadrieh commented
I hope that fixes it

2020-11-30 22:20 UTC, FSadrieh commented on evap/staff/forms.py
> +
I hope I fixed it

2020-12-01 09:43 UTC, janno42 approved these changes
Very nice first PR!
I noticed one additional thing you could do to make the error message even better than before if you want :)

2020-12-01 09:43 UTC, janno42 commented on evap/staff/forms.py
>                  raise forms.ValidationError(_('Duplicate contributor found. Each contributor should only be used once.'))
you could add the name of the duplicated contributor to the message like this:
```
raise forms.ValidationError(_('Duplicate contributor ({}) found. Each contributor should only be used once.').format(contributor.full_name))
```

2020-12-14 17:44 UTC, janno42 commented on evap/staff/tests/test_forms.py
> +        self.assertEqual(formset.non_form_errors(), ['Duplicate contributor(' + contributions-1-contributor ')found. Each contributor should only be used once.'])
Similar to how you created the message in the forms.py, you should use `contributor.full_name` as the string inserted into the error message. Pay attention: You forgot the second `+` and the spaces around the parentheses.

2021-01-10 11:13 UTC, janno42 approved these changes
thumbs up!

2021-01-10 11:14 UTC, merged