Fix various small mistakes with keyboard tabbing logic - also port to TypeScript
e-valuation/EvaP pull request #1656
Opened 2021-10-25 19:41 UTC by niklasmohrin

In addition to porting the file, this closes #1650

2021-10-31 17:13 UTC, niklasmohrin commented on evap/static/ts/src/student-vote.ts
> +const studentForm = document.getElementById("student-vote-form") as HTMLElement;
About the `const` error: I fixed it by using `type="module"` and not `type="text/javascript"` like it was before. I don't know why, but it works :D

About the other comment: I just aborted when either Ctrl of Alt is pressed

2021-11-01 11:24 UTC, janno42 reviewed
when submitting with some questions still missing answers, on the reloaded page i cannot start typing a text answer after tabbing somewhere.

2021-11-07 13:07 UTC, janno42 reviewed
- after submitting an incomplete form, unanswered questions are shown with the error class adding red borders. navigating with the arrow keys on the answer buttons of a rating question, the error class is not removed, although an answer is selected.
- when tabbing into the voting area, in the first row the first button is selected instead of the center option.

2021-11-15 17:30 UTC, He3lixxx approved these changes

2021-11-15 17:30 UTC, He3lixxx commented on evap/static/ts/src/student-vote.ts
> +const selectable: NodeListOf<HTMLElement> = studentForm.querySelectorAll(".tab-selectable");
`selectables`?

2021-11-15 17:40 UTC, He3lixxx approved these changes

2021-11-15 18:54 UTC, janno42 requested changes
after having submitted an incomplete form, the page reloads with all completely answered contributors closed. the card headers are then not tabbable, hence the cards cannot be opened via the keyboard.

2021-11-29 19:54 UTC, He3lixxx approved these changes

2021-11-29 20:12 UTC, merged