Update `Evaluation.State` values in log entries too
e-valuation/EvaP pull request #1686
Opened 2021-12-13 22:11 UTC by niklasmohrin

Closes #1678

2021-12-16 23:41 UTC, He3lixxx requested changes

2021-12-16 23:41 UTC, He3lixxx commented on evap/evaluation/migrations/0127_fix_logentry_types.py
> +    pass
Django already has this: https://docs.djangoproject.com/en/4.0/ref/migration-operations/#django.db.migrations.operations.RunPython.noop

2021-12-16 23:41 UTC, He3lixxx commented on evap/evaluation/migrations/0127_fix_logentry_types.py
> +    Note that 0123 is now modified to also take care of the logentries in thee first place.
```suggestion
    Note that 0123 is now modified to also take care of the logentries in the first place.
```

2021-12-20 19:48 UTC, janno42 approved these changes
✔️ Meets requirements

2021-12-20 19:52 UTC, He3lixxx approved these changes

2021-12-20 20:56 UTC, niklasmohrin commented
I noticed something else / for another PR: In the displayed log, the state names are always in English (also happens on master). This somewhat makes sense because we are displaying database value changes here and these are just these direct values, but since we are mapping them from integers to strings anyways, we _could_ also translate them while we are at it :D What do you think?

2021-12-20 20:59 UTC, merged

2021-12-21 16:46 UTC, janno42 commented
I would agree, that we *could* translate them, but it is not really necessary. Go ahead if you want to open an issue for that.

2022-01-06 22:23 UTC, niklasmohrin commented
See #1693