Add jump to unanswered question button
e-valuation/EvaP pull request #1750
Opened 2022-05-02 18:51 UTC by FranzSw

Adds a button to the error alert that allows a user to jump to the first unanswered question. (Design is up for discussion :D)

<img width="600" alt="image" src="https://user-images.githubusercontent.com/15076254/166307194-defda2ec-c9eb-4fef-8a7c-b365dfd87e3e.png">

2022-05-09 16:56 UTC, janno42 commented
okay, let's discuss the design :)
what do you think of a large button on the right hand side within the alert that is vertically centered and shows a `<span class="fa-solid fa-chevron-down"></span>` with the current text as a tooltip?

2022-05-16 19:59 UTC, niklasmohrin approved these changes

2022-05-23 16:35 UTC, janno42 requested changes

2022-05-23 16:35 UTC, janno42 commented on evap/student/templates/student_vote.html
> +                        <i class="fas fa-arrow-down"></i>
```suggestion
                        <i class="fas fa-chevron-down"></i>
```

2022-05-23 16:35 UTC, janno42 commented on evap/student/templates/student_vote.html
> +                    <button id="btn-jump-unanswered-question" type="button" class="btn btn-light btn-sm float-end" title="{% trans 'Jump to the first unanswered question' %}">
please make this a proper tooltip (with placement left)

2022-05-23 16:35 UTC, janno42 commented on evap/static/scss/components/_buttons.scss
> +}
```suggestion

```

you can remove this an use a regular button instead of a small one (see below)

2022-05-23 16:35 UTC, janno42 commented on evap/student/templates/student_vote.html
> +                    <button id="btn-jump-unanswered-question" type="button" class="btn btn-light btn-sm float-end" title="{% trans 'Jump to the first unanswered question' %}">
```suggestion
                    <button id="btn-jump-unanswered-question" type="button" class="btn btn-light float-end" title="{% trans 'Jump to the first unanswered question' %}">
```

2022-05-23 16:35 UTC, janno42 commented on evap/student/templates/student_vote.html
> +                <div class="p-2">
```suggestion
                <div>
```

2022-05-23 18:10 UTC, janno42 requested changes

2022-05-23 18:10 UTC, janno42 commented on evap/student/templates/student_vote.html
> +                <button id="btn-jump-unanswered-question" type="button" class="btn btn-light btn float-end" data-bs-toggle="tooltip" data-bs-placement="left" title="{% trans 'Jump to the first unansw
```suggestion
                <button id="btn-jump-unanswered-question" type="button" class="btn btn-light float-end" data-bs-toggle="tooltip" data-bs-placement="left" title="{% trans 'Jump to the first unanswered question' %}">
```

2022-05-23 20:35 UTC, He3lixxx approved these changes

2022-05-23 20:57 UTC, merged