Remove modal button ids
e-valuation/EvaP pull request #1755
Opened 2022-05-09 19:23 UTC by Kakadus

Fix #1722 

The functionality / appearance does not seem to be affected

2022-05-09 20:13 UTC, niklasmohrin requested changes
There is another

... in `evap/contributor/templates/contributor_evaluation_form.html:67`

Other than that, I checked the rendered code for the id from the feedback modal in the footer and it seems like it is unused

2022-05-30 16:21 UTC, niklasmohrin approved these changes

2022-05-30 16:22 UTC, He3lixxx approved these changes

2022-05-30 16:39 UTC, janno42 approved these changes
✔️ UI functionality checked

2022-05-30 17:11 UTC, merged