Add a button to swap main and other user in user merge view
e-valuation/EvaP pull request #1789
Opened 2022-08-08 16:19 UTC by postmartem

Closes #1781

2022-08-08 16:24 UTC, niklasmohrin commented on evap/staff/templates/staff_user_merge.html
> +        </div>
Nit: There is some extra whitespace here
```suggestion
        <h3>{% trans 'Merge users' %}</h3> 
        <div class="ms-auto"> 
            <a class="btn btn-sm btn-light" href="{% url 'staff:user_merge' main_user_id=other_user.pk other_user_id=main_user.pk %}">{% trans 'Swap main user' %}</a>
        </div>
```

2022-08-08 16:38 UTC, niklasmohrin approved these changes

2022-08-08 17:35 UTC, He3lixxx approved these changes
Nice, thanks! :)

2022-08-08 18:40 UTC, janno42 requested changes

2022-08-08 18:40 UTC, janno42 commented on evap/staff/templates/staff_user_merge.html
> +            <a class="btn btn-sm btn-light" href="{% url 'staff:user_merge' main_user_id=other_user.pk other_user_id=main_user.pk %}">{% trans 'Swap main user' %}</a>
```suggestion
            <a class="btn btn-sm btn-light" href="{% url 'staff:user_merge' main_user_id=other_user.pk other_user_id=main_user.pk %}">{% trans 'Swap users' %}</a>
```

2022-08-24 09:54 UTC, janno42 approved these changes

2022-08-24 09:54 UTC, janno42 commented
✔️ Meets requirements
✔️ UI functionality checked

2022-08-24 09:55 UTC, merged