Improve database sorting for user profiles
e-valuation/EvaP pull request #1794
Opened 2022-08-15 18:27 UTC by postmartem

Closes #1624

2022-08-15 19:31 UTC, niklasmohrin commented
The `FieldException` is a bug in django, they fixed it 3 months ago. We will update in the next couple of days

2022-09-12 16:36 UTC, niklasmohrin requested changes

2022-09-12 16:36 UTC, niklasmohrin commented on evap/evaluation/models.py
> +        return ", ".join([responsible.full_name for responsible in self.responsibles.all()])
```suggestion
        return ", ".join(responsible.full_name for responsible in self.responsibles.all())
```

2022-09-12 16:36 UTC, niklasmohrin commented on evap/evaluation/models.py
> +        ordering = [Lower(Concat("last_name", "first_name", "email"))]
sorry, we only now noticed that we may not want `Concat` afterall; it should just sort for the `Lower` of each individually

2022-09-12 16:36 UTC, niklasmohrin commented on evap/evaluation/tests/test_models.py
> +    def test_can_be_sorted(self):
I mean, they _can_ be sorted, but _are_ they? And is that sorting correct? Maybe `test_correct_sorting`?

2022-09-12 16:36 UTC, niklasmohrin commented on evap/evaluation/tests/test_models.py
> +        email_list = [user.email for user in user_list]
```suggestion
        email_list = [user.email for user in UserProfile.objects.all()]
```

2022-09-12 16:54 UTC, niklasmohrin commented on evap/evaluation/migrations/0131_alter_userprofile_options.py
> +# Generated by Django 4.0.6 on 2022-08-15 20:12
one more thing: Can you rename this file to `0131_userprofile_ordering.py`?

2022-09-12 16:54 UTC, niklasmohrin commented on evap/evaluation/tests/test_models.py
> +            last_name=iter(["B", "A", None]),
Strictly, this doesn't test that a) we `Lower` the fields and b) that there are more sorting keys than just the last name

2022-09-12 18:21 UTC, He3lixxx approved these changes

2022-09-12 18:40 UTC, niklasmohrin approved these changes

2022-09-12 18:40 UTC, merged