span layout not working yet
e-valuation/EvaP pull request #1931
Opened 2023-04-24 17:23 UTC by tanja04

closes #1820

2023-04-24 20:51 UTC, niklasmohrin approved these changes
Nice solution, thanks :)

2023-04-25 12:58 UTC, He3lixxx approved these changes
Nice, thank you :)

2023-05-06 10:00 UTC, janno42 requested changes
I'm gonna be a bit picky here. The current solution breaks the button group layout:
![image](https://user-images.githubusercontent.com/1781719/236617415-1814b2a3-de52-4254-a25f-69ceac7e56ce.png)

It should instead have rounded edges only at the outmost corners and not in between:
![image](https://user-images.githubusercontent.com/1781719/236617437-ff288374-dd42-4eaf-9ceb-a833959ba051.png)

Please have a look into the styling :)

2023-05-15 20:25 UTC, niklasmohrin approved these changes
Very nice :) One final thing:

2023-05-15 20:25 UTC, niklasmohrin commented on evap/static/scss/_utilities.scss
Please revert the changes on this file (we can show you in the next meeting)

2023-05-15 20:48 UTC, He3lixxx commented on evap/evaluation/templates/navbar.html
> +                                <button data-bs-toggle="tooltip" data-bs-placement="bottom" title="{% trans 'Staff mode' %}" type="submit" {% if user.is_staff %}class="btn btn-sm btn-navbar active"{%
Very minor thing: The classes `btn btn-sm btn-navbar` seem to be shared between the `if` and the `else` case, they could be moved out of the conditional code (like you did in line 94).

2023-05-22 16:32 UTC, janno42 approved these changes
✔️ Meets requirements
✔️ UI functionality checked

2023-05-22 16:34 UTC, janno42 commented
Very nice, thanks! 🎆

2023-05-22 16:34 UTC, merged