Fixed duplicate through email cleaning #1956
e-valuation/EvaP pull request #1979
Opened 2023-07-10 16:47 UTC by florian-str

Emails now get transformed before being validated / checked for duplicates in the edit form. Therefor, you can avoid accidentally triggering a database constraint.

2023-07-10 18:08 UTC, niklasmohrin requested changes
I don't think is exactly what we want, it feels a bit strange that we use our helper `clean_email` to compare to existing data, but still clean the email of this form here differently. I think it would be better if we would use `clean_email` directly on the email retrieved from `cleaned_data` and just have all the email cleaning in this one place - the call to `lower` later can then be removed too

2023-07-16 13:37 UTC, He3lixxx approved these changes
nice, thanks :)

2023-07-17 15:48 UTC, niklasmohrin approved these changes

2023-07-17 16:06 UTC, janno42 approved these changes
✔️ Meets requirements
✔️ UI functionality checked

2023-07-17 16:07 UTC, merged