Fix Borders in Outlined Button Group in textanswers view
e-valuation/EvaP pull request #2085
Opened 2023-12-04 20:05 UTC by fkoch-tgm

Fixes double borders referenced [here](https://github.com/e-valuation/EvaP/issues/1945#issuecomment-1819526342).

This needs the `:has()` pseudoselektor, which will be supported in the next firefox release [121](https://bugzilla.mozilla.org/show_bug.cgi?id=1858743)

![grafik](https://github.com/e-valuation/EvaP/assets/45557700/2234c722-b71c-4c55-98da-7ae30e9c1fc1)

2023-12-18 17:24 UTC, richardebeling reviewed
Code looks good to me, will have to test with firefox once 121 is released.

2023-12-18 17:24 UTC, richardebeling commented on evap/static/scss/components/_button-group.scss
> +}
missing newline

2024-01-08 19:17 UTC, janno42 commented on evap/static/scss/components/_button-group.scss
we should probably put this into `_adjustments.scss` to the other bootstrap styling fixes

2024-01-22 18:13 UTC, fkoch-tgm commented
@richardebeling I tried it using the new firefox and could not reproduce the issue anymore.

2024-01-22 20:40 UTC, janno42 approved these changes
Beautiful :)

2024-01-22 20:55 UTC, richardebeling approved these changes

2024-01-22 21:33 UTC, niklasmohrin commented
Just so we are on the same page: This is just a special case of #1945, right? Otherwise, we should link the PR and issue

2024-01-22 21:49 UTC, niklasmohrin requested changes
The scss is very long, I still have questions :D

2024-01-22 21:49 UTC, niklasmohrin commented on evap/static/scss/_adjustments.scss
> +    .btn:not(:last-child):not(.dropdown-toggle):has(+ :not(.btn-check[disabled])), .btn-group:not(:last-child) > .btn {
As far as I can tell, `.outline-fix .btn.dropdown-toggle` never matches on evap. I also don't know what it is supposed to fix

2024-01-22 21:49 UTC, niklasmohrin commented on evap/static/scss/_adjustments.scss
> +    .btn:not(:last-child):not(.dropdown-toggle):has(+ :not(.btn-check[disabled])), .btn-group:not(:last-child) > .btn {
Similar story: We don't have any `.outline-fix .btn-group`, so the part after the comma never matches either

2024-01-29 17:07 UTC, fkoch-tgm commented
@niklasmohrin I removed all unused CSS selectors.

I also checked again, if the issue still occurs on main and I could verify that there are double borders that happen on main but not on this branch.

2024-01-29 18:56 UTC, niklasmohrin approved these changes

2024-01-29 18:59 UTC, niklasmohrin commented
@janno42 Can you confirm that this closes everything from #1945?

2024-02-12 16:27 UTC, janno42 approved these changes
works for me and i'd say we can close #1945 then

2024-02-12 16:48 UTC, richardebeling approved these changes

2024-02-12 16:49 UTC, merged