Fix misplaced order icons: Make css selector for order icon padding more selective
e-valuation/EvaP pull request #2134
Opened 2024-03-04 19:14 UTC by richardebeling

fixes #2033

2024-03-04 19:26 UTC, Kakadus approved these changes

2024-03-04 19:41 UTC, Kakadus requested changes
Overlapping is fixed but still looks weired for me: 
![image](https://github.com/e-valuation/EvaP/assets/58814480/3d8c8f72-a18a-4108-a9d3-b7e4215b3c94)
The arrows should not be transparent but just gray, right?

2024-03-04 19:43 UTC, janno42 reviewed
Works for me but we should replace the opacity with gray and black font color to fix @Kakadus's issue

2024-03-14 18:56 UTC, janno42 approved these changes

2024-03-25 16:34 UTC, Kakadus approved these changes

2024-03-25 16:36 UTC, merged