remove incorrect db comment
e-valuation/EvaP pull request #2254
Opened 2024-07-29 19:18 UTC by fidoriel

2024-07-29 19:28 UTC, janno42 approved these changes

2024-07-29 20:14 UTC, richardebeling requested changes

2024-07-29 20:14 UTC, richardebeling commented on deployment/localsettings.template.py
> +        'PASSWORD': 'evap',
```suggestion
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'evap',
        'USER': 'evap',
        'PASSWORD': 'evap',
```

(We don't have auto-formatting for this file, I still don't want trailing spaces in here)

2024-08-01 20:05 UTC, richardebeling approved these changes
thanks

2024-08-01 20:06 UTC, merged